In [3]:
'''
Start by loading the dataset.[]
Display the following information:
A.  •First 10 rows
    •Shape & Datatypes
    •Summary statistics (mean,std,min,max)
'''
import pandas as pd
df_iris=pd.read_csv("IRIS.csv")
df_iris

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df_iris.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [5]:
df_iris.shape

(150, 5)

In [6]:
df_iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [11]:
df_iris.describe()
df_iris

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [12]:
# petal_length>4.5
df_iris["petal_length"]

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [13]:
df_iris[df_iris["petal_length"]>4.5]

     sepal_length  sepal_width  petal_length  petal_width          species
50            7.0          3.2           4.7          1.4  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor
54            6.5          2.8           4.6          1.5  Iris-versicolor
56            6.3          3.3           4.7          1.6  Iris-versicolor
58            6.6          2.9           4.6          1.3  Iris-versicolor
..            ...          ...           ...          ...              ...
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

[63 rows x 5 columns]

In [17]:
#species="Iris-virginica"
df_iris[df_iris["species"]=="Iris-virginica"].head()

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica

In [24]:
'''
group by species and compute
•Average sepal_length
•Maximum petal_width
•Standard deviation of sepal_width
'''
df_iris.groupby("species")["sepal_length"].mean() #avergae sepal_length
df_iris.groupby("species")["petal_width"].max() # Maximum petal_width
df_iris.groupby("species")["sepal_width"].std() #Standard deviation of sepal_width

df_iris.groupby("species").agg(
    average_sepal_length=("sepal_length","mean"),
    Maximum_petal_width=("petal_width","max"),
    Standard_deviation_of_sepal_width=("sepal_width","std"),
)

,average_sepal_length,Maximum_petal_width,Standard_deviation_of_sepal_width
species,,,
Iris-setosa,5.006,0.6,0.381024
Iris-versicolor,5.936,1.8,0.313798
Iris-virginica,6.588,2.5,0.322497

In [27]:
'''
# Create a new column:
D."petal_ratio"=petal_length/petal_width
•For each species,find the average petal_ratio
'''

df_iris["petal_ratio"]=df_iris["petal_length"]/df_iris["petal_width"]
df_iris.groupby("species")["petal_ratio"].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

In [30]:
'''
Question Start by loading the dataset
Display only columns: Name,Sex,Age,Fare,Survived
'''

df_titanic=pd.read_csv("Titanic-Dataset.csv")
df_titanic[['Name','Sex','Age','Fare','Survived']].head()

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0

In [33]:
#are female?
df_titanic[df_titanic['Sex']=="female"].head()

#fare > 30
df_titanic[df_titanic['Fare']>30].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S

In [34]:
'''
C.Group by Pclass
•Survival rate
•Average Fare
•Average Age
'''

df_titanic.groupby("Pclass").agg({
    "Survived":"mean",
    "Fare":"mean",
    "Age":"mean"
})

        Survived       Fare        Age
Pclass
1       0.629630  84.154687  38.233441
2       0.472826  20.662183  29.877630
3       0.242363  13.675550  25.140620